### ISSUE TITLE
Not a JPEG file: starts with 0x52 0x49

### ISSUE THREAD

**Issue by mxin262** [ymy-k/DPText-DETR#1]
Hi, thanks for your datasets. But I find that some pictures are wrong. Could you fix it?

**Comment by ymy-k** [comment]
Could you tell me which pictures are wrong and how you have this issue? Maybe somethind was wrong when I uploaded the images.

**Comment by ymy-k** [comment]
Could you tell me which pictures are wrong and how you have this issue? Maybe something was wrong when I uploaded the images

**Comment by mxin262** [comment]
It looks like this ![](https://user-images.githubusercontent.com/62656382/189883193-027a2f01-d5f0-4eff-a80d-256194d475c5.png). And I want to open the 0000000.jpg. 

Some errors have happened.
![截图_2022-09-13_18-55-35](https://user-images.githubusercontent.com/62656382/189883752-17d997e0-82a7-4d5a-94d0-80205d57e8d1.png)

My system is ubuntu.

**Comment by ymy-k** [comment]
I get it. These images are acutually downloaded from google webp format, so it seems that they are not supported to be viewed in the image reviewer of ubuntu system. Maybe you can try to use 'dwebp' command or other packages to process them first. I viewed them in windows system before and I will upload new images later.

**Comment by mxin262** [comment]
Thanks.  I will try it
