### ISSUE TITLE
How to get polygon coordinates of segmentation masks

### ISSUE THREAD

**Issue by annsilin** [ymy-k/DPText-DETR#10]
Hello! Thank you for your work! I'm trying to get coordinates of polygons that represent segmentation masks in `.txt` file after executing `demo/demo.py`, I want to use them to cut the input image into a bunch of small images that consist of detected text areas. Is there a way to do it?

**Comment by annsilin** [comment]
So far my solution is following:
In the file `demo/predictor.py` navigate to the function `run_on_image` (line 43) and add the following lines before the `return` statement:
`
        coordinates = []
        for polygon in instances.polygons.tolist():
            polygon = [[polygon[i], polygon[i + 1]] for i in range(0, len(polygon), 2)]
            coordinates.append(polygon)
`
This way we save all of the polygon coordinates as a list, the list would have the following format: `[[[x1, y1], [x2, y2], [x3, y3]], [x4, y4], [x5, y5], [x6, y6]]]` this example means that we have 2 polygons (triangles in this case) where the 1st polygon's coordinates are `[x1, y1], [x2, y2], [x3, y3]` and 2nd polygon's coordinates are `[x4, y4], [x5, y5], [x6, y6]`
Now to return our coordinates list add the `coordinates` variable to the end of the return statement.

Next in the file `demo/demo.py` add `import json` at the top, at line 88 change `predictions, visualized_output = demo.run_on_image(img)` to `predictions, visualized_output, coordinates = demo.run_on_image(img)` then after the line `visualized_output.save(out_filename)` add the following code:
`
                with open(out_filename + ".json", "w") as fp:
                    json.dump(coordinates, fp)
`
This way after executing `demo/demo.py` in the output folder we will get `.json` file with coordinates as well as visualized image.

**Comment by ymy-k** [comment]
yes, just save the point coordinates from instances.polygons
