### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Pujin-sysu** [ymy-k/DPText-DETR#11]
作者您好，很感谢您这篇工作。但我在编译环境时候遇到编译问题，尝试了一些解决办法都不成功，不知道是我哪里没有设置对
/home/pr-316/anaconda3/envs/DPText-DETR/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录

**Comment by ymy-k** [comment]
请确认是否正确安装设置CUDA，CUDA与pytorch版本是否对应等问题
