### ISSUE TITLE
Nice but instalation is only for the code writer, not for humans

### ISSUE THREAD

**Issue by hobbyofkings** [ymy-k/DPText-DETR#12]
Your work is interesting to 10 people in the world and you made a code that is understandable with hints, in other words, a setup text is just for you.  
Download dataset. Where to put it? Create a new folder in the directory or look it up somewhere.?
Polygon3 library is dead. error: legacy-install-failure ,   ERROR: Failed building wheel for Polygon3
pip install detectron2 - dead. Tried to clone but 16 tools not working properly.  
Running got error: ./datasets/totaltext/train_poly_ori.json is missing... 

I wish to use it but there is no way to solve your puzzle.

**Comment by ymy-k** [comment]
I never have the installation error of Polygon3 and detectron2. I am not responsible to teach you how to configure all basic environment settings. It seems that you didn't download the json file. I uploaded it.
