### ISSUE TITLE
关于论文中3.2节Positional Label Form的问题

### ISSUE THREAD

**Issue by Zoeun** [ymy-k/DPText-DETR#17]
“If the original top side of text instance lies in the bottom position, the starting point is adjusted to the other side” 这段话我不知道该如何理解，‘’如果文本实例的原始顶部位于底部位置，则将起始点调整到另一侧‘’，那如何判断文本实例的顶部和底部呢？

**Comment by ymy-k** [comment]
从坐标空间意义上去判断，可以参考[process_positional_label.py](https://github.com/ymy-k/DPText-DETR/blob/main/process_positional_label.py)
