### ISSUE TITLE
大佬，请问您的旋转数据增强是怎么实现的呢

### ISSUE THREAD

**Issue by 6098669** [ymy-k/DPText-DETR#2]
为什么我在TSETR中加了这个代码，即使训练了很多个epoch，检测性能反而还下降了呢
![23cd3ac6d7594d1e](https://user-images.githubusercontent.com/68067132/194793882-dde4af3d-7d12-44df-bb7d-f096353d2b90.png)

**Comment by ymy-k** [comment]
我实验的时候是用离线处理好的旋转数据以及标签形式进行训练的，方便统计旋转数据里有多少inverse-like实例，所以如果像您这样在线处理的话数据增强的顺序应该是：旋转->随机裁剪->随机缩放

**Comment by ymy-k** [comment]
如果是先裁剪再旋转的话，由于codebase会给旋转后的图片padding，由于旋转角度比较大会导致后续随机缩放的时候文本的尺寸就相对较小了，应该这个会影响性能

**Comment by ymy-k** [comment]
如果是先裁剪再旋转的话，codebase会给旋转后的图片padding，由于旋转角度比较大会导致后续随机缩放的时候文本的尺寸就相对较小了，应该这个会影响性能

**Comment by 6098669** [comment]
非常感谢大佬的解惑，我是仿照ABCNetV2的数据增强来的，因为我看ABCNetv2就是先裁剪再旋转的。您看这样之后，随机缩放的参数添加多少合适呀。
![58b4dfdeecf74f28](https://user-images.githubusercontent.com/68067132/194795086-76cefa19-d389-411d-a89c-78fc42754cb2.png)

**Comment by ymy-k** [comment]
其实只要设self.augmentation.insert(0, T.RandomRotation()), self.augmentation.insert(1, RandomCropInstance())就行，不用改size的大小了

**Comment by ymy-k** [comment]
ABCNetv2虽然写了旋转增强但好像源码设置里并没有用到

**Comment by 6098669** [comment]
大佬，非常感谢，我看ABCNetV2在icdar2015中也用到了旋转，您看我这么设置是对的了吧。对了，我之前也加了随机翻转，也掉点了，可能也是这个原因吧
![4385ba10ffdd39d8](https://user-images.githubusercontent.com/68067132/194796187-ff69d47c-4096-47b9-89b5-bb956e9888a7.png)

**Comment by ymy-k** [comment]
嗯这样顺序应该没问题，但是要提一点，角度里头你得加一个0°，不然没有无旋转角度的样本，并且这些角度再转180°的角度可以加上，可以比较全面地涵盖文本顺序，以我实验来看TESTR虽然识别指标收敛上比较慢，但是最后反向文本地识别是可以学出来比较好的效果的。如果你是用TESTR在syntext上预训练的模型做初始化的话，finetune的学习率得调大(lr5e-5, backbone5e-6，可以降一次学习率)，因为原来的模型没用旋转，相应训练步数也调多(大概finetune50000k)效果才比较好

**Comment by ymy-k** [comment]
嗯这样顺序应该没问题，但是要提一点，角度里头你得加一个0°，不然没有无旋转角度的样本，并且这些角度再转180°的角度可以加上，可以比较全面地涵盖文本顺序，以我实验来看TESTR虽然识别指标收敛上比较慢，但是最后反向文本的识别是可以学出来比较好的效果的。如果你是用TESTR在syntext上预训练的模型做初始化的话，finetune的学习率得调大(lr5e-5, backbone5e-6，可以降一次学习率)，因为原来的模型没用旋转，相应训练步数也调多(大概finetune50000k)效果才比较好

**Comment by ymy-k** [comment]
嗯这样顺序应该没问题，但是要提一点，角度里头你得加一个0°，不然没有无旋转角度的样本，并且这些角度再转180°的角度可以加上，可以比较全面地涵盖文本顺序，以我实验来看TESTR虽然识别指标收敛上比较慢，但是最后反向文本的识别是可以学出来比较好的效果的。如果你是用TESTR在syntext上预训练的模型做初始化的话，finetune的学习率得调大(lr5e-5, backbone5e-6，可以降一次学习率)，因为原来的模型没用旋转，相应训练步数也调多(大概finetune50k)效果才比较好

**Comment by ymy-k** [comment]
PS:(不是大佬，受不起orz

**Comment by 6098669** [comment]
> PS:(不是大佬，受不起orz
您太谦虚了，若不是您的指点，我这辈子都想不明白会是因为这种原因掉点的。非常感谢，我先按照您说的试一试

**Comment by 6098669** [comment]
哥，您说的对，顺序确实错了，我又试了两次，发现不掉点了，但也没涨点。我是8个batch训练200k，只训练TESTR的检测分支，F-score竟然还是只有82左右。您能否告知一下您是怎么离线处理旋转数据的呀，我想再试一下，非常感谢，呜呜呜。

**Comment by ymy-k** [comment]
可以看下训练参数的config文件吗

**Comment by 6098669** [comment]
> 可以看下训练参数的config文件吗

![181045e40e693a1f](https://user-images.githubusercontent.com/68067132/195103101-9bc26064-f97c-4776-b78d-77a5f507e388.png)
您看，不知对不对，我只改了STEPS和MAX_ITER，预训练模型是R-50.pkl。

**Comment by ymy-k** [comment]
STEPS可以往后调一些，比如160K，可能也和测试参数有关，我TotalText上的检测模型都是用的短边1000，长边1600这个尺寸，你可以试一下，你这是没有synthtext预训练的吗，如果没训练可以把INFERENCE_TH_TEST调低一些

**Comment by 6098669** [comment]
> STEPS可以往后调一些，比如160K，可能也和测试参数有关，我TotalText上的检测模型都是用的短边1000，长边1600这个尺寸，你可以试一下，你这是没有synthtext预训练的吗，如果没训练可以把INFERENCE_TH_TEST调低一些

老哥，请问不用synthtext预训练的情况下，BASE_LR和LR_BEACKBONE应该多少合适呀，为啥我加了旋转之后，BASE_LR为1e-4经常不收敛，有时候训练4-5次才会收敛一次，于是我又调小了学习率。

**Comment by ymy-k** [comment]
原来1e-4, 1e-5就可以。tensorboard保存的loss曲线啥样，evaluation的精度在训练中怎么变化的，还有你的模型网络是怎么改的。我没有碰到过不收敛的问题。可视化过数据增强后标签没有问题吗，也有可能你在线处理的几个旋转角度得多加几个0°上去

**Comment by 6098669** [comment]
> 原来1e-4, 1e-5就可以。tensorboard保存的loss曲线啥样，evaluation的精度在训练中怎么变化的，还有你的模型网络是怎么改的。我没有碰到过不收敛的问题。可视化过数据增强后标签没有问题吗，也有可能你在线处理的几个旋转角度得多加几个0°上去

非常感谢，模型我并没有做任何改变，就是不加旋转1e-4能收敛，加了不容易收敛，而且角度也加不了180°，加了就报错。我先再加几个0试试。大佬您问的太高深了，惭愧惭愧，我现在还不太会tensorboard和可视化。

**Comment by 6098669** [comment]
> 

呜呜呜，就是原始的testr，学习率我设置成5e-5，旋转数据增强我又加了几个0，还是不容易收敛，训练10万iter，检测结果还是0。老哥，能否加下你的微信呀，有偿请教，问了您这么多实在不好意思。

**Comment by ymy-k** [comment]
检测结果是0肯定有问题，有把检测部分拎出来写一个网络并且把loss、matching、evaluation都对应修改吗，就算是原网络(包括了识别分支decoder)也不至于一直是0

**Comment by 6098669** [comment]
> 检测结果是0肯定有问题，有把检测部分拎出来写一个网络并且把loss、matching、evaluation都对应修改吗，就算是原网络(包括了识别分支decoder)也不至于一直是0

额，竟然这么复杂，我再训练一次原网络试试

**Comment by ymy-k** [comment]
https://github.com/mlpc-ucsd/TESTR/issues/7，你用的R-50.pkl应该不是这个问题吧......

**Comment by ymy-k** [comment]
你用的R-50.pkl应该不是这个问题吧...... https://github.com/mlpc-ucsd/TESTR/issues/7

**Comment by ymy-k** [comment]
> 如果你是用TESTR在syntext上预训练的模型做初始化的话，finetune的学习率得调大(lr5e-5, backbone5e-6，可以降一次学习率)，因为原来的模型没用旋转，相应训练步数也调多(大概finetune50k)效果才比较好

如果用的原网络，为啥不试一下加载testr synthtext预训练的模型来做finetune看效果呢，你这起步100K试错成本有点大

**Comment by 6098669** [comment]
> > 如果你是用TESTR在syntext上预训练的模型做初始化的话，finetune的学习率得调大(lr5e-5, backbone5e-6，可以降一次学习率)，因为原来的模型没用旋转，相应训练步数也调多(大概finetune50k)效果才比较好
> 
> 如果用的原网络，为啥不试一下加载testr synthtext预训练的模型来做finetune看效果呢，你这起步100K试错成本有点大

我的r-50.pkl好像没啥问题。大佬说的对，我先在syntext预训练模型上试试。之前我错误的以为syntext预训练结果都很高了，加不加旋转对比可能不明显。谢谢大佬指点

**Comment by 6098669** [comment]
哥，目前我在syntext预训练模型上试了tsetr代码，的确涨点了，但是在r-50.pkl上试了试旋转，就是不涨点，跪求您的totaltext的旋转数据集，我想再试一试可以么

**Comment by 6098669** [comment]
哥，主要我就是想着靠一些数据增强来涨涨点，然后我再随便扯一些不管有没有用的模块加上去，最后结果涨点了也好看，就想靠这个水一水论文😬

**Comment by ymy-k** [comment]
> 哥，目前我在syntext预训练模型上试了tsetr代码，的确涨点了，但是在r-50.pkl上试了试旋转，就是不涨点，跪求您的totaltext的旋转数据集，我想再试一试可以么

写下代码把训练图片和控制点标签、bbox一起旋转就行了，然后在线数据增强把旋转的去掉按原流程，可以参考detectron2上的数据处理部分。如果你只需要检测，还是建议把识别部分decoder和loss等去掉

**Comment by 6098669** [comment]
> > 哥，目前我在syntext预训练模型上试了tsetr代码，的确涨点了，但是在r-50.pkl上试了试旋转，就是不涨点，跪求您的totaltext的旋转数据集，我想再试一试可以么
> 
> 写下代码把训练图片和控制点标签、bbox一起旋转就行了，然后在线数据增强把旋转的去掉按原流程，可以参考detectron2上的数据处理部分。如果你只需要检测，还是建议把识别部分decoder和loss等去掉

哥，有偿购买您的这个离线增强的代码可以不，要是可以正好可以拿这个当做这周的进展了😬。 我是跨考生，代码能力太弱了，代码都看不太懂，万分感谢。

**Comment by 6098669** [comment]
> > > 哥，目前我在syntext预训练模型上试了tsetr代码，的确涨点了，但是在r-50.pkl上试了试旋转，就是不涨点，跪求您的totaltext的旋转数据集，我想再试一试可以么
> > 
> > 
> > 写下代码把训练图片和控制点标签、bbox一起旋转就行了，然后在线数据增强把旋转的去掉按原流程，可以参考detectron2上的数据处理部分。如果你只需要检测，还是建议把识别部分decoder和loss等去掉
> 
> 哥，有偿购买您的这个离线增强的代码可以不，要是可以正好可以拿这个当做这周的进展了😬。 我是跨考生，代码能力太弱了，代码都看不太懂，万分感谢。

哥，6098669就是我的qq号😬

**Comment by ymy-k** [comment]
别别别不至于，最近在赶论文，这几天有空的时候我把旋转的totaltext数据传一下把链接放这

**Comment by 6098669** [comment]
> 别别别不至于，最近在赶论文，这几天有空的时候我把旋转的totaltext数据传一下把链接放这

感谢感谢(*^ω^*)

**Comment by ymy-k** [comment]
链接：https://pan.baidu.com/s/1-JJ9ZkzW7VXCJN10IfoYEg 
提取码：sbv4 
旋转后的原标签

**Comment by ymy-k** [comment]
链接：https://pan.baidu.com/s/1-JJ9ZkzW7VXCJN10IfoYEg 
提取码：sbv4 
旋转后的训练图片和原标签

**Comment by 6098669** [comment]
> 链接：https://pan.baidu.com/s/1-JJ9ZkzW7VXCJN10IfoYEg 提取码：sbv4 旋转后的训练图片和原标签

感谢感谢哥

**Comment by 6098669** [comment]
哥，我没问题了，您可以关闭这个issue啦，您给的离线的图片太多了，我试了一下还掉点了就不想再试了，好像在线-15  0  15这样能略微涨点，但我也就试过一次，不试了不试了
