### ISSUE TITLE
请问代码什么时候能开源呢

### ISSUE THREAD

**Issue by ocrhei** [ymy-k/DPText-DETR#3]
非常棒的工作

**Comment by ymy-k** [comment]
感谢关注，审稿结束后将开源。实现其实很简单，有任何问题可以随时与我交流~

**Comment by ocrhei** [comment]
您好，目前我有一个小样本脚手架分割的项目，需要用到数据扩充，导师让我离线扩充，可是我并不太会。能否购买一下您的旋转增强的代码呢，或者您帮我扩充下，价格不是问题。
