### ISSUE TITLE
Installation not working without cuda

### ISSUE THREAD

**Issue by filipelauarqantev** [ymy-k/DPText-DETR#4]
Hello, 

I am trying to do the installation locally where I don't have a GPU. I downloaded pytorch and torchvision without the cuda extension and the setup.py command is not working.

How can properly make the installations without cuda?

Thanks in advance,
Filipe Lauar.

**Comment by ymy-k** [comment]
Hi, I haven't tried the installation without cuda. You may refer to the Adelaidet codebase.
