### ISSUE TITLE
Performance on ICDAR2015

### ISSUE THREAD

**Issue by Apostatee** [ymy-k/DPText-DETR#6]
Thanks for sharing this amazing work which achieves excellent performances on these datasets with texts in irregular shape. Have you verified the effectiveness of DPText-DETR on ICDAR2015 dataset? since it is a comman benchmark scene text detection dataset.

**Comment by ymy-k** [comment]
Hi~ Thanks. As for the performance on ICDAR2015, I haven't test DPText-DETR on it. But I guess the F-measure will be aroud 90% using proper training and testing strategy. In my another work DeepSolo which also uses point queries, the detection F-measure is about 90%. And the performance of TESTR on ICDAR2015 can also be a rough reference.

**Comment by Apostatee** [comment]
Thanks!

**Comment by Hardik1608** [comment]
> Hi~ Thanks. As for the performance on ICDAR2015, I haven't test DPText-DETR on it. But I guess the F-measure will be aroud 90% using proper training and testing strategy. In my another work DeepSolo which also uses point queries, the detection F-measure is about 90%. And the performance of TESTR on ICDAR2015 can also be a rough reference.

I am getting the F-measure around 50% when using the weights finetuned on the Total-text dataset. What changes do I need to make to improve these results, or If I have my own custom dataset?
