### ISSUE TITLE
如何训练自己的数据集呢

### ISSUE THREAD

**Issue by 921162820** [ymy-k/DPText-DETR#7]
我自己数据集的json文件没有poly，请问poly该如何生成呢

**Comment by ymy-k** [comment]
hi，标注的形式可以参考论文。如果希望检测结果更贴合文本轮廓可以参考ABCNet仓库提供的代码先生成Bezier控制点（上下边各四个），然后参考process_positional_label.py中代码在上下边拟合的Bezier曲线上各采8个点（按顺时针排列），即可得到所需的原始的poly点标注。当然，直接在你标注中文本上下边直接均匀取点应该也是可以的

**Comment by ymy-k** [comment]
hi，标注的形式可以参考论文。如果希望检测结果更贴合文本轮廓可以参考ABCNet仓库提供的代码先生成Bezier控制点（上下边各四个），然后参考process_positional_label.py中代码在上下边拟合的Bezier曲线上各采8个点（按顺时针排列），即可得到所需的原始的poly点标注。直接在你标注中文本上下边均匀取点应该也是可以的

**Comment by 921162820** [comment]
感谢作者的回复，但我发现生成贝塞尔曲线需要标注中的前一半跟后一半分别是两个长边，但我的并不是，所以不太会生成，请问这种情况有解决办法不

**Comment by ymy-k** [comment]
你的标注是什么形式的呢，是否能做一些处理取到两个边？

**Comment by 921162820** [comment]
> 你的标注是什么形式的呢，是否能做一些处理取到两个边？
感谢您的回复，我当初标注的太随意了。就是随机选一个初始点，然后每个轮廓标注的点数还不一样。    请问是不是得用固定的点，并且初始点位置固定，按顺序标呢。   像我那种点数不固定，初始位置不固定的数据集应该是没办法使用您的代码了吧， 处理的话目前的话能力有限还没想好怎么处理。

**Comment by ymy-k** [comment]
起始点如果都是左上和右下倒没问题。轮廓点数的话，如果是一个文本的上下边点数不一样可能比较麻烦，需要判断上下各几个点。如果不同文本点数不一样但是都是双数倒没问题，都处理成同一数量就行。标注形式不统一的话，建议试试用分割类的方法会更方便一些

**Comment by Taoqi0402** [comment]
> hi，标注的形式可以参考论文。如果希望检测结果更贴合文本轮廓可以参考ABCNet仓库提供的代码先生成Bezier控制点（上下边各四个），然后参考process_positional_label.py中代码在上下边拟合的Bezier曲线上各采8个点（按顺时针排列），即可得到所需的原始的poly点标注。直接在你标注中文本上下边均匀取点应该也是可以的

你好作者，我想问一下，生成的生成Bezier控制点是8个，但是我看见process_positional_label.py要求的Bezier控制点是16个，totaltext的train_poly_rotate_ori.json控制点也是16个
