### ISSUE TITLE
Can not run the inference code

### ISSUE THREAD

**Issue by eslambakr** [ymy-k/DPText-DETR#9]
Dears,

Thank for sharing your nice work!

But unfortunately, I can not run the inference code, as I am facing the following error:
KeyError: 'Non-existent config key: MODEL.TRANSFORMER'

I added this line to solve it:
cfg.set_new_allowed(args.config_file)

Then, I faced this error:
KeyError: "No object named 'TransformerPureDetector' found in 'META_ARCH' registry!"

Therefore your help will be much appreciated!
Thanks in advance!

**Comment by ymy-k** [comment]
It seems that there is something wrong with the environment and installation. Please make sure the Adelaidet codebase is correctly built.

**Comment by eslambakr** [comment]
It works for me after fixing the environment.
Thanks!

**Comment by ymy-k** [comment]
nice
